### ISSUE TITLE
Does not deploy

### ISSUE THREAD

**Issue by ryansonshine** [MauriceBrg/cognito-alb-fargate-demo#2]
When attempting a `cdk deploy` the following error is given:

```
11:03:36 AM | CREATE_FAILED        | AWS::Lambda::Function                     | certificateCertifi...orFunction5D4BA95F
Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. 
```

**Comment by MauriceBrg** [comment]
Hey :)

I haven't touched the code in a while, seems like I need to update the CDK version etc. as well, quite a few of these components are now out of date. I can't promise you that I'll get to it quickly unfortunately :/

**Comment by MauriceBrg** [comment]
Hey @ryansonshine ,

I've updated the repo to CDK v2 and after upgrading a few more dependencies it works again, give it a try :)
